name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  check:
    name: Check
    runs-on: nixos
    steps:
      - uses: actions/checkout@v4
      - run: nix flake check --no-warn-dirty
